name: Publish Docker Container

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Docker Container
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Packages
        run: docker login ghcr.io -u felipecosta09 --password ${{ secrets.GH_TOKEN }} 

      - name: Build Docker Image
        run: docker build -t docker.pkg.github.com/felipecosta09/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker Image to GitHub Packages
        run: docker push docker.pkg.github.com/felipecosta09/${{ env.IMAGE_NAME }}:latest
