name: Scan Container Image

on:
  workflow_dispatch:
env:
  TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
  IMAGE_NAME: "ghcr.io/felipecosta09/cve-2024-3094"

jobs:
  scan:
    name: Scan Container Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install TMAS
        run: sudo curl -s -L https://gist.githubusercontent.com/felipecosta09/a3d0cf68f4e85fc53bd6d295c1bb2c5b/raw/fafd525ef1bccfe7a460ec29e5f6d8aca397448a/tmas_install.sh | bash
          
      - name: Check for the CVE 2024-3094
        run: |
          echo ${{ env.IMAGE_NAME }} | bash cve2024-3094.sh

      - name: Deploy to Prod?
        run: echo "Deploying to Prod"
