name: Scan Container Image

on:
  workflow_dispatch:
env:
  TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}

jobs:
  publish:
    name: Scan Container Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "ghcr.io/felipecosta09/cve-2024-3094"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run the Script
        run: |
          echo ${{ env.IMAGE_NAME }} | bash cve2024-3094.sh

      - name: Deploy to Prod?
        run: echo "Deploying to Prod"
